// AUTO-GENERATED by `supabase gen types typescript`
// Run: npx supabase gen types typescript --local > types/supabase.ts
// This file is a placeholder — regenerate after running migrations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: "rider" | "driver" | "operator" | "super_admin";
          full_name: string;
          phone: string | null;
          registered_as_driver: boolean;
          strikes: number;
          is_suspended: boolean;
          average_rating: number | null;
          rating_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: "rider" | "driver" | "operator" | "super_admin";
          full_name: string;
          phone?: string | null;
          registered_as_driver?: boolean;
          strikes?: number;
          is_suspended?: boolean;
          average_rating?: number | null;
          rating_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: "rider" | "driver" | "operator" | "super_admin";
          full_name?: string;
          phone?: string | null;
          registered_as_driver?: boolean;
          strikes?: number;
          is_suspended?: boolean;
          average_rating?: number | null;
          rating_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      driver_profiles: {
        Row: {
          id: string;
          dni: string;
          license_number: string;
          license_category: string;
          availability: "online" | "offline";
          current_lat: number | null;
          current_lng: number | null;
          location_updated_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          dni: string;
          license_number: string;
          license_category: string;
          availability?: "online" | "offline";
          current_lat?: number | null;
          current_lng?: number | null;
          location_updated_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dni?: string;
          license_number?: string;
          license_category?: string;
          availability?: "online" | "offline";
          current_lat?: number | null;
          current_lng?: number | null;
          location_updated_at?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "driver_profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      vehicles: {
        Row: {
          id: string;
          rider_id: string;
          license_plate: string;
          make_model: string;
          color: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          rider_id: string;
          license_plate: string;
          make_model: string;
          color: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          rider_id?: string;
          license_plate?: string;
          make_model?: string;
          color?: string;
          is_active?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "vehicles_rider_id_fkey";
            columns: ["rider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      services: {
        Row: {
          id: string;
          rider_id: string;
          driver_id: string | null;
          vehicle_id: string;
          status:
            | "requested"
            | "assigned"
            | "en_route"
            | "in_progress"
            | "completed"
            | "cancelled";
          pickup_address: string;
          pickup_lat: number;
          pickup_lng: number;
          destination_address: string;
          destination_lat: number;
          destination_lng: number;
          estimated_price: number | null;
          estimated_pickup_km: number | null;
          estimated_ride_km: number | null;
          estimated_return_km: number | null;
          final_price: number | null;
          final_pickup_km: number | null;
          final_ride_km: number | null;
          final_return_km: number | null;
          price_per_km_at_time: number | null;
          cancellation_reason: string | null;
          cancelled_by: string | null;
          requested_at: string;
          assigned_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
        };
        Insert: {
          id?: string;
          rider_id: string;
          driver_id?: string | null;
          vehicle_id: string;
          status?: "requested";
          pickup_address: string;
          pickup_lat: number;
          pickup_lng: number;
          destination_address: string;
          destination_lat: number;
          destination_lng: number;
          estimated_price?: number | null;
          estimated_pickup_km?: number | null;
          estimated_ride_km?: number | null;
          estimated_return_km?: number | null;
          requested_at?: string;
        };
        Update: {
          id?: string;
          rider_id?: string;
          driver_id?: string | null;
          vehicle_id?: string;
          status?:
            | "requested"
            | "assigned"
            | "en_route"
            | "in_progress"
            | "completed"
            | "cancelled";
          final_price?: number | null;
          final_pickup_km?: number | null;
          final_ride_km?: number | null;
          final_return_km?: number | null;
          price_per_km_at_time?: number | null;
          cancellation_reason?: string | null;
          cancelled_by?: string | null;
          assigned_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "services_rider_id_fkey";
            columns: ["rider_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "services_driver_id_fkey";
            columns: ["driver_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "services_vehicle_id_fkey";
            columns: ["vehicle_id"];
            isOneToOne: false;
            referencedRelation: "vehicles";
            referencedColumns: ["id"];
          }
        ];
      };
      service_status_log: {
        Row: {
          id: string;
          service_id: string;
          from_status:
            | "requested"
            | "assigned"
            | "en_route"
            | "in_progress"
            | "completed"
            | "cancelled"
            | null;
          to_status:
            | "requested"
            | "assigned"
            | "en_route"
            | "in_progress"
            | "completed"
            | "cancelled";
          changed_by: string;
          changed_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          service_id: string;
          from_status?:
            | "requested"
            | "assigned"
            | "en_route"
            | "in_progress"
            | "completed"
            | "cancelled"
            | null;
          to_status:
            | "requested"
            | "assigned"
            | "en_route"
            | "in_progress"
            | "completed"
            | "cancelled";
          changed_by: string;
          changed_at?: string;
          notes?: string | null;
        };
        Update: Record<string, never>;
        Relationships: [
          {
            foreignKeyName: "service_status_log_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          }
        ];
      };
      ratings: {
        Row: {
          id: string;
          service_id: string;
          rater_id: string;
          ratee_id: string;
          stars: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          service_id: string;
          rater_id: string;
          ratee_id: string;
          stars: number;
          comment?: string | null;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [
          {
            foreignKeyName: "ratings_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          }
        ];
      };
      pricing_config: {
        Row: {
          id: number;
          price_per_km: number;
          updated_by: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          price_per_km: number;
          updated_by: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          price_per_km?: number;
          updated_by?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "rider" | "driver" | "operator" | "super_admin";
      driver_availability: "online" | "offline";
      service_status:
        | "requested"
        | "assigned"
        | "en_route"
        | "in_progress"
        | "completed"
        | "cancelled";
    };
    CompositeTypes: Record<string, never>;
  };
};
